### ISSUE TITLE
Function to write a new geotransform for a raster subset?

### ISSUE THREAD

**Issue by Chris35Wills** [atedstone/georaster#3]
Following the opening of a raster to a set extent e.g.

```
ras=georaster.SingleBandRaster(msk_f, \
						    load_data=(x_min, x_max, y_min, y_max), \
						    latlon=False)
```

the geotransform info accessed by ras.ds.GetGeoTransform() points back to the full dataset (not the subset). This makes writing the subset raster out using georaster.write-simple_tiff() more cumbersome with regard to the required geotransform argument. Perhaps a function like this would be useful:

```
def redefine_geotransform(tl_x, tl_y, post, rotation=0):
	'''
	Set up geotransform info

	Returns: 

	Geotransform tuple object 

	geotransform[0] /* top left x */
	geotransform[1] /* w-e pixel resolution */
	geotransform[2] /* rotation, 0 if image is "north up" */
	geotransform[3] /* top left y */
	geotransform[4] /* rotation, 0 if image is "north up" */
	geotransform[5] /* n-s pixel resolution */
	'''

	geotransform = np.zeros(6)
	geotransform[0] = tl_x
	geotransform[1] = post
	geotransform[2] = rotation
	geotransform[3] = tl_y
	geotransform[4] = rotation
	geotransform[5] = -post

	geotransform=geotransform.tolist()

	return geotransform
```

**Comment by atedstone** [comment]
fixed in commit 7e534900203. Rather than create a new function, now when a raster is opened with a requested subset area (using load_data=(area)), self.trans is updated to match that subset area.
